spring:
  data:
    mongodb:
      host: localhost
      database: account-service
      port: 27017

wisdomGate:
  app:
    jwtCookieName:
      abdel
    jwtSecret:
      abdelPassword
    jwtExpiration:
      86400000